import asyncio
from collections.abc import Callable, Coroutine
from typing import Any, Protocol

from app.agent.state import ResearchState
from app.models.evidence import Evidence
from app.models.research import ResearchStep
from app.tools.base import (
    ToolExecutionError,
)


class SearchToolProtocol(Protocol):
    async def search(
        self,
        query: str,
        research_step_id: str,
        max_results: int,
    ) -> list[Evidence]: ...


ResearcherNode = Callable[
    [ResearchState],
    Coroutine[Any, Any, dict[str, Any]],
]


async def mock_researcher_node(
    state: ResearchState,
) -> dict[str, Any]:
    return {
        "evidence": state.get(
            "evidence",
            [],
        ),
        "iteration": (state.get("iteration", 0) + 1),
    }


def create_researcher_node(
    search_tool: SearchToolProtocol,
    max_results: int,
    max_tool_calls: int,
) -> ResearcherNode:
    async def search_step(
        step: ResearchStep,
    ) -> tuple[
        ResearchStep,
        list[Evidence],
        str | None,
    ]:
        try:
            results = await search_tool.search(
                query=step.question,
                research_step_id=step.id,
                max_results=max_results,
            )

            updated_step = step.model_copy(update={"status": "completed"})

            return (
                updated_step,
                results,
                None,
            )

        except ToolExecutionError as exc:
            updated_step = step.model_copy(update={"status": "failed"})

            error = f"{step.id}: {exc}"

            return (
                updated_step,
                [],
                error,
            )

    async def researcher_node(
        state: ResearchState,
    ) -> dict[str, Any]:
        retry_queries = state.get(
            "retry_queries",
            [],
        )

        current_iteration = state.get(
            "iteration",
            0,
        )

        existing_plan = state.get(
            "plan",
            [],
        )

        existing_evidence = state.get(
            "evidence",
            [],
        )

        current_tool_calls = state.get(
            "tool_calls",
            0,
        )

        state_max_tool_calls = state.get(
            "max_tool_calls",
            max_tool_calls,
        )

        remaining_tool_calls = max(
            state_max_tool_calls - current_tool_calls,
            0,
        )

        if retry_queries:
            active_steps = [
                ResearchStep(
                    id=(f"retry-{current_iteration + 1}-{index}"),
                    question=query,
                    rationale=("Targeted retry generated by the verifier."),
                    status="pending",
                )
                for index, query in enumerate(
                    retry_queries,
                    start=1,
                )
            ]

        else:
            active_steps = [step for step in existing_plan if step.status == "pending"]

        active_steps = active_steps[:remaining_tool_calls]

        if not active_steps:
            return {
                "retry_queries": [],
                "iteration": (current_iteration + 1),
            }

        results = await asyncio.gather(*(search_step(step) for step in active_steps))

        new_evidence: list[Evidence] = []

        executed_steps: list[ResearchStep] = []

        new_errors: list[str] = []

        for (
            step,
            step_evidence,
            error,
        ) in results:
            executed_steps.append(step)

            new_evidence.extend(step_evidence)

            if error is not None:
                new_errors.append(error)

        if retry_queries:
            updated_plan = [
                *existing_plan,
                *executed_steps,
            ]

        else:
            updated_by_id = {step.id: step for step in executed_steps}

            updated_plan = [
                updated_by_id.get(
                    step.id,
                    step,
                )
                for step in existing_plan
            ]

        return {
            "plan": updated_plan,
            "evidence": [
                *existing_evidence,
                *new_evidence,
            ],
            "retry_queries": [],
            "iteration": (current_iteration + 1),
            "tool_calls": (current_tool_calls + len(active_steps)),
            "errors": [
                *state.get(
                    "errors",
                    [],
                ),
                *new_errors,
            ],
        }

    return researcher_node
